services:
  base: &base-spec
    build: .
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
  main:
    <<: *base-spec
    volumes:
      - .:/pwndbg

  ubuntu22.04:
    <<: *base-spec
    image: ghcr.io/pwndbg/pwndbg:ubuntu22.04
    pull_policy: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        image: ubuntu:22.04

  ubuntu24.04:
    <<: *base-spec
    image: ghcr.io/pwndbg/pwndbg:ubuntu24.04
    pull_policy: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        image: ubuntu:24.04

  ubuntu24.04-mount:
    <<: *base-spec
    image: ghcr.io/pwndbg/pwndbg:ubuntu24.04
    pull_policy: always
    build:
      context: .
      target: base
      dockerfile: Dockerfile
      args:
        image: ubuntu:24.04
    volumes:
      - .:/pwndbg

  debian12:
    <<: *base-spec
    image: ghcr.io/pwndbg/pwndbg:debian12
    pull_policy: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        image: debian:12

  archlinux:
    <<: *base-spec
    image: ghcr.io/pwndbg/pwndbg:archlinux
    pull_policy: always
    build:
      context: .
      dockerfile: Dockerfile.arch
      args:
        image: archlinux:latest

  fedora41:
    <<: *base-spec
    image: ghcr.io/pwndbg/pwndbg:fedora41
    pull_policy: always
    build:
      context: .
      dockerfile: Dockerfile.dnf
      args:
        image: fedora:41

  fedora42:
    <<: *base-spec
    image: ghcr.io/pwndbg/pwndbg:fedora42
    pull_policy: always
    build:
      context: .
      dockerfile: Dockerfile.dnf
      args:
        image: fedora:42

  fedora43:
    <<: *base-spec
    image: ghcr.io/pwndbg/pwndbg:fedora43
    pull_policy: always
    build:
      context: .
      dockerfile: Dockerfile.dnf
      args:
        image: fedora:43
