site_url: https://pwndbg.re/pwndbg/
site_name: Documentation
site_description: >-
  pwndbg (/paʊnˈdiˌbʌɡ/) is a GDB plug-in that makes debugging with GDB suck less, with a focus on features needed by low-level software developers, hardware hackers, reverse-engineers and exploit developers.

# Repository
repo_name: pwndbg/pwndbg
repo_url: https://github.com/pwndbg/pwndbg/
theme:
  logo: assets/icon.png
  name: material
  custom_dir: docs/theme
  font:
    text: Roboto
    code: Roboto Mono
  features:
    # - navigation.footer
    - content.code.annotate
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.integrate
    - toc.follow
  palette: 
    scheme: slate
    primary: black
    accent: purple

  favicon: assets/favicon.ico
  icon:
    logo:logo

# Plugins
plugins:
  - blog
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  # - git-committers:
  #     repository: pwndbg/pwndbg
  #     branch: dev
  #     exclude:
  #       - index.md
  #       - docs/commands/**
  - gen-files:
      scripts:
        - scripts/gen_ref_pages.py
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: []
          # load_external_modules: true
          options:
            allow_inspection: true
            show_source: false
            show_bases: true
            docstring_style: google
            docstring_section_style: table
            show_root_full_path: true
            show_if_no_docstring: true
            show_docstring_classes: true
            show_docstring_modules: true
            show_docstring_description: true
            show_docstring_examples: true
            show_docstring_other_parameters: true
            show_docstring_parameters: true
            show_docstring_return: true
            show_docstring_raises: true
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags 

# Additional configuration
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pwndbg
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/pwndbg/
    - icon: fontawesome/brands/discord
      link: https://discord.gg/x47DssnGwm
  # Page status
  status:
    new: New
    deprecated: Deprecated
  generator: false

extra_css:
  - stylesheets/extra.css

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - fenced_code
  - toc:
      permalink: true
      toc_depth : "1-2"
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  # - pymdownx.emoji:
  #     emoji_generator: !!python/name:material.extensions.emoji.to_svg
  #     emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      auto_title: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav: 
  - Home: index.md
  # - Getting started: getting_started.md
  - Setup: setup.md
  # - Features: features.md
  - Commands: commands/index.md
  - Source: source/index.md
  # - FAQ: faq.md
  - Blog: blog/index.md
