authors:
  disconnect3d:
    name: Disconnect3d
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/10009354
    url: https://github.com/disconnect3d
  nikoshell:
    name: Niko
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/150354584
    url: https://github.com/nikoshell
