from __future__ import annotations

from enum import Enum
from typing import Protocol

from elftools.elf.relocation import Relocation


class LibcType(Enum):
    GLIBC = "glibc"
    MUSL = "musl"
    UNKNOWN = "unknown"


class Libc(Protocol):
    def type(self) -> LibcType: ...
    def is_being_used(self) -> bool: ...
    def initialize(self) -> bool: ...
    def version(self) -> tuple[int, ...]: ...
    def has_symbols(self) -> bool: ...
    def has_debug_info(self) -> bool: ...
    def filename(self) -> str: ...
    def loader_filename(self) -> str: ...
    def mapping(self) -> str: ...
    def loader_mapping(self) -> str: ...
    def section_by_name(self, section_name: str) -> tuple[int, int, bytes] | None: ...
    def section_address_by_name(self, section_name: str) -> int: ...
    def relocations_by_section_name(self, section_name: str) -> tuple[Relocation, ...]: ...
    def source_url(self) -> str: ...
