from __future__ import annotations

from enum import Enum
from typing import Protocol


class LibcType(Enum):
    GLIBC = "glibc"
    MUSL = "musl"
    UNKNOWN = "unknown"


class Libc(Protocol):
    def is_being_used(self) -> bool: ...
    def initialize(self) -> bool: ...
    def get_version(self) -> tuple[int, ...]: ...
    def type(self) -> LibcType: ...
    def has_symbols(self) -> bool: ...
    def has_debug_info(self) -> bool: ...
    def source_url(self) -> str: ...
    def filename(self) -> str: ...
    def loader_filename(self) -> str: ...
    def mapping(self) -> str: ...
    def loader_mapping(self) -> str: ...
