#!/usr/bin/env python
"""
You should use scripts/generate_docs.sh and scripts/verify_docs.sh instead
of using this.

If the PWNDBG_GEN_DOC_JUST_VERIFY environment variable
is set, then    : Exit with non-zero exit status if the docs/functions/ files
                  aren't up to date with the sources. Don't modify anything.

If it isn't, this fixes up the docs/functions/ files to be up
to date with the information from the sources.
"""

from __future__ import annotations

from typing import Dict
from inspect import getmodule
from inspect import signature
from mdutils.mdutils import MdUtils

import pwndbg
from pwndbg.gdblib.functions import _GdbFunction
from scripts._gen_docs_generic import verify_existence, update_files_simple, verify_files_simple


def extract_functions() -> Dict[str, _GdbFunction]:
    """
    Returns a dictionary that mapes function names to
    the corresponding _GdbFunction objects.
    """
    functions = pwndbg.gdblib.functions.functions
    result = {}

    for f in functions:
        result[f.name] = f

    return result


def convert_to_markdown(named_funcs: Dict[str, _GdbFunction]) -> str:
    """
    Returns a dict which maps filenames to their markdown contents.
    It will have only one item (the index.md).
    """
    markdowned = {}

    mdFile = MdUtils(index_path)
    mdFile.new_header(level=1, title="Functions")
    intro_text = """
pwndbg provides a set of functions which can be used during expression evaluation to
quickly perform common calculations. These can even be passed to other commands as arguments.
Currently, they only work in gdb.

To see a list of all functions, including those built into gdb, use `help function`. To see
the help of any given function use `help function function_name`. Function invokation must
include a preceding $ sign and must include brackets. For instance, invoke the `environ`
function like so:
```
pwndbg> p $environ("LANG")
$2 = (signed char *) 0x7fffffffe6da "LANG=en_US.UTF-8"
```
Make sure to escape the function argument quotes if the result of the function is being passed
to a pwndbg command:
```
pwndbg> tele $environ(\\"LANG\\")
00:0000│  0x7fffffffede0 ◂— 'LANG=en_US.UTF-8'
01:0008│  0x7fffffffede8 ◂— 'US.UTF-8'
02:0010│  0x7fffffffedf0 ◂— 0x313d53454e494c00
[...]
```
## pwndbg functions
    """
    mdFile.new_paragraph(intro_text.strip())

    for func_name, func in named_funcs.items():
        mdFile.new_paragraph(f"### **{func_name}**")
        func_signature = f"""
``` {{.python .no-copy}}
{func_name}{str(signature(func.func)).replace("'", "")}
```
"""
        mdFile.new_paragraph(func_signature)
        mdFile.new_paragraph("#### Description\n" + func.__doc__.replace("Example:", "#### Example"))
        mdFile.new_paragraph("-"*10)

    hide_nav = "---\nhide:\n  - navigation\n---\n"
    autogen_warning = "<!-- THIS WHOLE FILE IS AUTOGENERATED. DO NOT MODIFY IT. See scripts/generate_docs.sh -->"
    markdowned[index_path] = hide_nav + autogen_warning + "\n" + mdFile.get_md_text()
    return markdowned


def check_index(scoped_params: Dict[str, list[Parameter]]):
    assert (
        len(scoped_params.keys()) == 3
        and "It seems a new scope has been added, "
        f"please update the index file ({index_path}) and bump this number accordingly."
    )


base_path = "docs/functions/"  # Must have trailing slash.
index_path = base_path + "index.md"

# ==== Start ====

if len(sys.argv) > 1:
    print("This script doesn't accept any arguments.")
    print("See top of the file for usage.")
    exit(3)

just_verify = False
if os.getenv("PWNDBG_GEN_DOC_JUST_VERIFY"):
    just_verify = True

print("\n==== Function Documentation ====")

named_functions = extract_functions()
markdowned = convert_to_markdown(named_functions)
assert(len(markdowned) == 1) # Only index.md

if just_verify:
    print("Checking if all files are in place..")
    missing, extra = verify_existence(list(markdowned.keys()), base_path)
    if missing or extra:
        print("To add mising files please run ./scripts/generate_docs.sh.")
        print("To remove extra files please remove them manually.")
        exit(555)
    print("Every file is where it should be!")

    print("Verifying contents...")
    err = verify_files_simple(markdowned)
    if err:
        print("VERIFICATION FAILED. The files differ from what would be auto-generated.")
        print("Error:", err)
        print("Please run ./scripts/generate_docs.sh from project root and commit the changes.")
        exit(777)

    print("Verification successful!")
else:
    print("Updating files...")
    update_files_simple(markdowned)
    print("Update successful.")

    missing, extra = verify_existence(list(markdowned.keys()), base_path)
    assert not missing and "Some files (and not the index) are missing, which should be impossible."

    if extra:
        print("Please delete the extra files by hand.")
        exit(888)
