name: build base pwndbg image

on:
  push:
    branches:
      - dev
    paths:
      - 'uv.lock'
      - 'Dockerfile.base-apt'
  pull_request:
    paths:
      - 'uv.lock'
      - 'Dockerfile.base-apt'

permissions:
  contents: read
  packages: write

jobs:
  base-image:
    strategy:
      matrix:
        platform_base:
          - platform: linux/amd64
            base_image: debian:13
            runner: ubuntu-latest

          - platform: linux/arm/v7
            base_image: debian:13
            runner: ubuntu-latest

          - platform: linux/arm64
            base_image: debian:13
            runner: ubuntu-24.04-arm

          - platform: linux/386
            base_image: debian:13
            runner: ubuntu-24.04-arm

          - platform: linux/ppc64le
            base_image: debian:13
            runner: ubuntu-24.04-arm

          - platform: linux/riscv64
            base_image: debian:13
            runner: ubuntu-24.04-arm

          - platform: linux/s390x
            base_image: debian:13
            runner: ubuntu-24.04-arm

          - platform: linux/loong64
            base_image: ghcr.io/loong64/debian:trixie
            runner: ubuntu-24.04-arm

    runs-on: ${{ matrix.platform_base.runner }}
    continue-on-error: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker buildx build \
            --progress=plain \
            --platform ${{ matrix.platform_base.platform }} \
            --build-arg image=${{ matrix.platform_base.base_image }} \
            -f ./Dockerfile.base-apt \
            -t ghcr.io/pwndbg/base-apt:latest \
            .
      - name: Push Docker image
        if: github.ref == 'refs/heads/dev'
        run: |
          docker buildx build \
            --progress=plain \
            --platform ${{ matrix.platform_base.platform }} \
            --build-arg image=${{ matrix.platform_base.base_image }} \
            -f ./Dockerfile.base-apt \
            -t ghcr.io/pwndbg/base-apt:latest \
            --push .
