name: Stable Release Docs

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy docs for stable release
    runs-on: ubuntu-latest
    steps:
      - name: Only allow running on tag refs
        if: ${{ github.ref_type != 'tag' }}
        run: |
          echo "You must run this workflow in the context of a tag."
          exit 1

      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0

      - name: Install latest uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          version: "latest"

      - name: Install dependencies
        run: uv sync --group docs

      - name: Update docs/index.md with README.md
        run: uv run ./scripts/generate-readme.py

      - name: Deploy site
        run: |
          # mike pushes commits to the gh-pages branch
          git config --global user.email "doc-bot@pwndbg.re"
          git config --global user.name "DocBot"
          git fetch --no-tags --prune --depth=1 origin +refs/heads/gh-pages:refs/remotes/origin/gh-pages
          uv run --group docs mike deploy \
            --update-aliases \
            --push \
            --remote origin \
            ${{ github.ref_name }} \
            stable
